### PR TITLE
#15 did some UI improvements

### LINKED ISSUE #15: UI needs to be improved
Instead of having the links stacked by the side, create a header and lay them out horizontally.
Additionally would be nice if the entire app was dark themed.

image
This part would probably look nicer if the form itself was vertical. The inputs could also have a bit of padding to look more modern.

image
Ditto here, make these task boxes look more modern, and easier to read/use for the user

### PR DESCRIPTION
**Pull request by dennisxu54**
closes #15

### CODE REVIEW

**Comment by dennisxu54** [comment]
image

image

**Review by egodihc — CHANGES_REQUESTED** [review]
Make the form vertical please, also where my dark theme?

**Comment by dennisxu54** [comment]
image

image

**Review by egodihc — COMMENTED** [review]
Add a bit of margin between each task card

**Review by egodihc — COMMENTED** [review]
Also a bit more padding on the buttons

**Comment by dennisxu54** [comment]
image

**Comment by dennisxu54** [comment]
image

**Review by egodihc — APPROVED** [review]
I think this appears in a level above satisfactory in a subjective manner according to your's truly

**Pull request merged**
